# Generated by Django 5.0.6 on 2025-06-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('preview', models.CharField(max_length=250, verbose_name='preview')),
                ('content', models.TextField(verbose_name='content')),
                ('date', models.DateField(verbose_name='date')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
            ],
        ),
    ]
