# Generated by Django 5.2.1 on 2025-06-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(default='Default content', verbose_name='content'),
        ),
    ]
